name: CI

on:
  push:
    branches:
      - master
    paths:
      - packages/worklog/src/**
      - packages/worklog/src-tauri/**
      - packages/worklog/static/**
      - packages/worklog/package.json
      - packages/worklog/bun.lock
      - packages/worklog/svelte.config.js
      - packages/worklog/tsconfig.json
      - packages/worklog/vite.config.js
      - .github/workflows/ci.yml
  pull_request:
    paths:
      - packages/worklog/src/**
      - packages/worklog/src-tauri/**
      - packages/worklog/static/**
      - packages/worklog/package.json
      - packages/worklog/bun.lock
      - packages/worklog/svelte.config.js
      - packages/worklog/tsconfig.json
      - packages/worklog/vite.config.js
      - .github/workflows/ci.yml
  workflow_dispatch:

env:
  CI: true

jobs:
  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: packages/worklog
        run: bun install --frozen-lockfile

      - name: Type and Svelte checks
        working-directory: packages/worklog
        run: bun run check

      - name: Build frontend
        working-directory: packages/worklog
        run: bun run build


  # REMOVED BECAUSE MOSTLY IT'S FAILS BECAUSE OF THE FRONTEND BUILDING
  # tauri-build:
  #   name: Tauri Binary Build
  #   runs-on: ubuntu-24.04

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install Linux system dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y \
  #           build-essential \
  #           pkg-config \
  #           libgtk-3-dev \
  #           libwebkit2gtk-4.1-dev \
  #           libappindicator3-dev \
  #           librsvg2-dev \
  #           patchelf

  #     - name: Setup Bun
  #       uses: oven-sh/setup-bun@v2

  #     - name: Install frontend dependencies
  #       working-directory: packages/worklog
  #       run: bun install --frozen-lockfile

  #     - name: Setup Rust toolchain
  #       uses: dtolnay/rust-toolchain@stable

  #     - name: Cache Rust dependencies
  #       uses: Swatinem/rust-cache@v2
  #       with:
  #         workspaces: packages/worklog/src-tauri

  #     - name: Build Tauri binary (no bundle)
  #       working-directory: packages/worklog
  #       run: bun tauri build --no-bundle
